//! Language registry for tree-sitter grammars.
//!
//! Manages available languages and provides language lookup by name or alias.
//! Grammars are compiled from source during the build process.

use std::collections::HashMap;
use tree_sitter::Language;

// Include the FFI bindings generated by build.rs
include!(concat!(env!("OUT_DIR"), "/grammar_ffi.rs"));

/// Registry containing all supported languages.
pub struct LanguageRegistry {
    /// Map from language name to tree-sitter Language
    languages: HashMap<String, Language>,
    /// Map from alias to canonical language name
    aliases: HashMap<String, String>,
}

impl LanguageRegistry {
    /// Create a new language registry with all supported languages.
    pub fn new() -> Self {
        let mut registry = Self {
            languages: HashMap::new(),
            aliases: HashMap::new(),
        };
        
        // Register all languages compiled from source
        let languages = [
            ("ada", "ada"),
            ("adl", "adl"),
            ("agda", "agda"),
            ("alloy", "alloy"),
            ("amber", "amber"),
            ("astro", "astro"),
            ("awk", "awk"),
            ("bash", "bash"),
            ("basic", "basic"),
            ("bass", "bass"),
            ("beancount", "beancount"),
            ("bibtex", "bibtex"),
            ("bicep", "bicep"),
            ("bitbake", "bitbake"),
            ("blade", "blade"),
            ("blueprint", "blueprint"),
            ("bovex", "bovex"),
            ("c", "c"),
            ("c-sharp", "c-sharp"),
            ("c3", "c3"),
            ("caddyfile", "caddyfile"),
            ("cairo", "cairo"),
            ("capnp", "capnp"),
            ("cel", "cel"),
            ("chuck", "chuck"),
            ("clarity", "clarity"),
            ("clojure", "clojure"),
            ("cmake", "cmake"),
            ("comment", "comment"),
            ("cpon", "cpon"),
            ("cpp", "cpp"),
            ("crystal", "crystal"),
            ("css", "css"),
            ("csv", "csv"),
            ("cue", "cue"),
            ("cylc", "cylc"),
            ("cython", "cython"),
            ("d", "d"),
            ("dart", "dart"),
            ("dbml", "dbml"),
            ("debian", "debian"),
            ("devicetree", "devicetree"),
            ("dhall", "dhall"),
            ("diff", "diff"),
            ("djot", "djot"),
            ("dockerfile", "dockerfile"),
            ("dot", "dot"),
            ("doxyfile", "doxyfile"),
            ("dtd", "dtd"),
            ("dunstrc", "dunstrc"),
            ("earthfile", "earthfile"),
            ("edoc", "edoc"),
            ("eex", "eex"),
            ("eiffel", "eiffel"),
            ("elisp", "elisp"),
            ("elixir", "elixir"),
            ("elm", "elm"),
            ("elvish", "elvish"),
            ("embedded-template", "embedded-template"),
            ("erlang", "erlang"),
            ("fennel", "fennel"),
            ("fga", "fga"),
            ("fidl", "fidl"),
            ("fish", "fish"),
            ("flatbuffers", "flatbuffers"),
            ("forth", "forth"),
            ("freebasic", "freebasic"),
            ("fsharp", "fsharp"),
            ("gas", "gas"),
            ("gdscript", "gdscript"),
            ("gherkin", "gherkin"),
            ("ghostty", "ghostty"),
            ("git-config", "git-config"),
            ("git-rebase", "git-rebase"),
            ("gitattributes", "gitattributes"),
            ("gitcommit", "gitcommit"),
            ("gitignore", "gitignore"),
            ("gleam", "gleam"),
            ("glsl", "glsl"),
            ("gn", "gn"),
            ("gnuplot", "gnuplot"),
            ("go", "go"),
            ("go-format-string", "go-format-string"),
            ("godot-resource", "godot-resource"),
            ("gomod", "gomod"),
            ("gotmpl", "gotmpl"),
            ("gowork", "gowork"),
            ("gpr", "gpr"),
            ("graphql", "graphql"),
            ("gren", "gren"),
            ("groovy", "groovy"),
            ("hare", "hare"),
            ("haskell", "haskell"),
            ("haskell-literate", "haskell-literate"),
            ("haskell-persistent", "haskell-persistent"),
            ("haxe", "haxe"),
            ("hcl", "hcl"),
            ("hdl", "hdl"),
            ("heex", "heex"),
            ("hocon", "hocon"),
            ("hoon", "hoon"),
            ("hosts", "hosts"),
            ("html", "html"),
            ("htmldjango", "htmldjango"),
            ("hurl", "hurl"),
            ("hyprlang", "hyprlang"),
            ("iex", "iex"),
            ("ini", "ini"),
            ("ink", "ink"),
            ("inko", "inko"),
            ("janet-simple", "janet-simple"),
            ("java", "java"),
            ("javascript", "javascript"),
            ("jinja2", "jinja2"),
            ("jjdescription", "jjdescription"),
            ("jjrevset", "jjrevset"),
            ("jjtemplate", "jjtemplate"),
            ("jq", "jq"),
            ("jsdoc", "jsdoc"),
            ("json", "json"),
            ("json5", "json5"),
            ("jsonnet", "jsonnet"),
            ("julia", "julia"),
            ("just", "just"),
            ("kcl", "kcl"),
            ("kconfig", "kconfig"),
            ("kdl", "kdl"),
            ("klog", "klog"),
            ("koka", "koka"),
            ("kotlin", "kotlin"),
            ("koto", "koto"),
            ("ld", "ld"),
            ("ldif", "ldif"),
            ("lean", "lean"),
            ("ledger", "ledger"),
            ("less", "less"),
            ("llvm", "llvm"),
            ("llvm-mir", "llvm-mir"),
            ("log", "log"),
            ("lpf", "lpf"),
            ("lua", "lua"),
            ("lua-format-string", "lua-format-string"),
            ("luap", "luap"),
            ("luau", "luau"),
            ("mail", "mail"),
            ("make", "make"),
            ("markdoc", "markdoc"),
            ("matlab", "matlab"),
            ("mermaid", "mermaid"),
            ("meson", "meson"),
            ("mojo", "mojo"),
            ("move", "move"),
            ("nasm", "nasm"),
            ("nearley", "nearley"),
            ("nginx", "nginx"),
            ("nickel", "nickel"),
            ("nim", "nim"),
            ("nix", "nix"),
            ("nu", "nu"),
            ("odin", "odin"),
            ("ohm", "ohm"),
            ("opencl", "opencl"),
            ("openscad", "openscad"),
            ("org", "org"),
            ("pascal", "pascal"),
            ("passwd", "passwd"),
            ("pem", "pem"),
            ("penrose", "penrose"),
            ("perl", "perl"),
            ("pest", "pest"),
            ("picat", "picat"),
            ("pkl", "pkl"),
            ("po", "po"),
            ("pod", "pod"),
            ("ponylang", "ponylang"),
            ("powershell", "powershell"),
            ("prisma", "prisma"),
            ("properties", "properties"),
            ("proto", "proto"),
            ("prql", "prql"),
            ("pug", "pug"),
            ("purescript", "purescript"),
            ("python", "python"),
            ("ql", "ql"),
            ("qmljs", "qmljs"),
            ("query", "query"),
            ("quint", "quint"),
            ("r", "r"),
            ("regex", "regex"),
            ("rego", "rego"),
            ("requirements", "requirements"),
            ("rescript", "rescript"),
            ("robot", "robot"),
            ("robots", "robots"),
            ("ron", "ron"),
            ("rshtml", "rshtml"),
            ("rst", "rst"),
            ("ruby", "ruby"),
            ("rust", "rust"),
            ("rust-format-args", "rust-format-args"),
            ("scala", "scala"),
            ("scfg", "scfg"),
            ("scheme", "scheme"),
            ("scss", "scss"),
            ("shellcheckrc", "shellcheckrc"),
            ("slang", "slang"),
            ("slint", "slint"),
            ("slisp", "slisp"),
            ("smali", "smali"),
            ("smithy", "smithy"),
            ("sml", "sml"),
            ("snakemake", "snakemake"),
            ("solidity", "solidity"),
            ("sourcepawn", "sourcepawn"),
            ("spade", "spade"),
            ("spicedb", "spicedb"),
            ("sql", "sql"),
            ("sshclientconfig", "sshclientconfig"),
            ("strace", "strace"),
            ("strictdoc", "strictdoc"),
            ("supercollider", "supercollider"),
            ("svelte", "svelte"),
            ("sway", "sway"),
            ("swift", "swift"),
            ("systemverilog", "systemverilog"),
            ("t32", "t32"),
            ("tablegen", "tablegen"),
            ("tact", "tact"),
            ("task", "task"),
            ("tcl", "tcl"),
            ("teal", "teal"),
            ("templ", "templ"),
            ("tera", "tera"),
            ("textproto", "textproto"),
            ("thrift", "thrift"),
            ("tlaplus", "tlaplus"),
            ("todotxt", "todotxt"),
            ("toml", "toml"),
            ("tsx", "tsx"),
            ("twig", "twig"),
            ("typescript", "typescript"),
            ("typespec", "typespec"),
            ("typst", "typst"),
            ("ungrammar", "ungrammar"),
            ("unison", "unison"),
            ("uxntal", "uxntal"),
            ("vala", "vala"),
            ("vento", "vento"),
            ("verilog", "verilog"),
            ("vhdl", "vhdl"),
            ("vhs", "vhs"),
            ("vim", "vim"),
            ("werk", "werk"),
            ("wesl", "wesl"),
            ("wgsl", "wgsl"),
            ("wikitext", "wikitext"),
            ("wit", "wit"),
            ("xit", "xit"),
            ("xml", "xml"),
            ("xtc", "xtc"),
            ("yaml", "yaml"),
            ("yara", "yara"),
            ("yuck", "yuck"),
            ("zig", "zig"),
        ];
        
        for (name, ffi_name) in languages {
            if let Some(lang) = get_language(ffi_name) {
                registry.register(name, lang);
            }
        }
        
        // Register common aliases
        registry.register_aliases("javascript", &["js", "ecmascript"]);
        registry.register_aliases("python", &["py"]);
        registry.register_aliases("rust", &["rs"]);
        registry.register_aliases("typescript", &["ts"]);
        registry.register_aliases("cpp", &["c++", "cc", "cxx"]);
        registry.register_aliases("bash", &["sh", "shell", "zsh"]);
        registry.register_aliases("markdown", &["md", "mkd"]);
        registry.register_aliases("yaml", &["yml"]);
        registry.register_aliases("c-sharp", &["c#", "cs", "csharp"]);
        registry.register_aliases("fsharp", &["f#", "fsharp"]);
        registry.register_aliases("go", &["golang"]);
        registry.register_aliases("ruby", &["rb"]);
        registry.register_aliases("php", &["php3", "php4", "php5"]);
        registry.register_aliases("perl", &["pl"]);
        registry.register_aliases("java", &["jsp"]);
        registry.register_aliases("scala", &["sc"]);
        registry.register_aliases("kotlin", &["kt", "kts"]);
        registry.register_aliases("swift", &["swiftlang"]);
        registry.register_aliases("lua", &["lua54", "lua53", "lua51"]);
        registry.register_aliases("haskell", &["hs"]);
        registry.register_aliases("ocaml", &["ml"]);
        registry.register_aliases("elixir", &["ex", "exs"]);
        registry.register_aliases("erlang", &["erl"]);
        registry.register_aliases("clojure", &["clj", "cljs"]);
        registry.register_aliases("scheme", &["scm", "racket"]);
        registry.register_aliases("r", &["rscript"]);
        registry.register_aliases("julia", &["jl"]);
        registry.register_aliases("dart", &["flutter"]);
        registry.register_aliases("dockerfile", &["docker", "dockerignore"]);
        registry.register_aliases("sql", &["mysql", "postgresql", "postgres", "sqlite"]);
        registry.register_aliases("json", &["json5", "jsonc"]);
        registry.register_aliases("xml", &["svg", "xsl", "xslt"]);
        registry.register_aliases("toml", &["cargo_toml"]);
        registry.register_aliases("ini", &["conf", "config", "properties"]);
        registry.register_aliases("make", &["makefile", "mk"]);
        registry.register_aliases("cmake", &["cmakelists"]);
        registry.register_aliases("typescript", &["ts", "typescript"]);
        registry.register_aliases("tsx", &["typescript-react", "typescriptreact"]);
        registry.register_aliases("jsx", &["javascript-react", "javascriptreact", "react"]);
        registry.register_aliases("objective-c", &["objc", "objectivec", "obj-c"]);
        registry.register_aliases("objective-cpp", &["objcpp", "objectivecpp"]);
        registry.register_aliases("scala", &["sc"]);
        registry.register_aliases("perl", &["pl", "pm"]);
        registry.register_aliases("powershell", &["ps1", "pwsh"]);
        registry.register_aliases("php", &["php3", "php4", "php5", "php7"]);
        
        registry
    }
    
    /// Register a language with its tree-sitter Language.
    pub fn register(&mut self, name: &str, language: Language) {
        self.languages.insert(name.to_lowercase(), language);
    }
    
    /// Register aliases for a language.
    pub fn register_aliases(&mut self, canonical: &str, aliases: &[&str]) {
        for alias in aliases {
            self.aliases.insert(alias.to_lowercase(), canonical.to_lowercase());
        }
    }
    
    /// Get a language by name or alias.
    ///
    /// Returns `Some(Language)` if found, `None` otherwise.
    pub fn get_language(&self, name: &str) -> Option<Language> {
        let name_lower = name.to_lowercase();
        
        // Try direct lookup first
        if let Some(lang) = self.languages.get(&name_lower) {
            return Some(lang.clone());
        }
        
        // Try alias lookup
        if let Some(canonical) = self.aliases.get(&name_lower) {
            return self.languages.get(canonical).map(|l| l.clone());
        }
        
        None
    }
    
    /// Check if a language is supported.
    pub fn is_supported(&self, name: &str) -> bool {
        self.get_language(name).is_some()
    }
    
    /// Get list of all supported language names.
    pub fn supported_languages(&self) -> Vec<&str> {
        self.languages.keys().map(|s| s.as_str()).collect()
    }
}

impl Default for LanguageRegistry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_registry_creation() {
        let registry = LanguageRegistry::new();
        assert!(registry.languages.len() > 0);
    }
    
    #[test]
    fn test_get_language() {
        let registry = LanguageRegistry::new();
        
        // Test some common languages
        assert!(registry.get_language("rust").is_some() || !registry.languages.contains_key("rust"));
        assert!(registry.get_language("python").is_some() || !registry.languages.contains_key("python"));
    }
    
    #[test]
    fn test_aliases() {
        let registry = LanguageRegistry::new();
        
        // Test alias lookup
        if registry.languages.contains_key("javascript") {
            assert!(registry.get_language("js").is_some());
        }
        if registry.languages.contains_key("python") {
            assert!(registry.get_language("py").is_some());
        }
    }
    
    #[test]
    fn test_is_supported() {
        let registry = LanguageRegistry::new();
        
        // At least some languages should be supported
        assert!(registry.languages.len() > 0);
    }
}